version: '3.8'

services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ".env"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql

  api:
    build: backend/
    container_name: api
    restart: always
    env_file:
      - ".env"
    ports:
      - 8000:8000
    depends_on:
      - db
